Repository snayyar00/accessibility-widget, pull requests merged in 2025-07, with the labels that each got.

#149 validations, sanitization and malicious input prevention
  api/package-lock.json
  api/package.json
  api/services/authentication/login.service.ts
  api/services/authentication/register.service.ts
  api/services/user/update-user.service.ts
  api/utils/sanitization.helper.ts
  api/utils/validation-errors.helper.ts
  api/validations/authenticate.validation.ts
  app/package-lock.json
  app/package.json
  app/src/components/Auth/SignUpForm.tsx
  app/src/containers/Auth/SignUp.tsx
  app/src/containers/Profile/InformationSetting.tsx
  app/src/locales/en.json
  app/src/utils/errorHandler.ts
Labels: Possible security concern, Review effort 4/5

#161 Pdf report UI improved
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Accessibility/ReportView.tsx
  app/src/utils/getWidgetSettings.ts
  mta-sts.txt
Labels: Possible security concern, Review effort 4/5

#157 No email on signup
  api/services/authentication/register.service.ts
  app/src/containers/Dashboard/Dashboard.tsx
  app/src/utils/applyStatusClass.ts
Labels: Review effort 3/5, Possible security concern

#173 Pdf report UI improved
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Accessibility/ReportView.tsx
  app/src/utils/getWidgetSettings.ts
Labels: Review effort 4/5

#156 Email validation for maximum length
  api/package-lock.json
  api/repository/prices.repository.ts
  api/server.ts
  api/services/authentication/forgot-password.service.ts
  api/services/problemReport/reportProblem.ts
  api/services/teams/teams.service.ts
  api/services/user/user.service.ts
  api/validations/authenticate.validation.ts
  api/validations/email.validation.ts
  app/src/containers/Auth/ForgotPassword.tsx
  app/src/containers/Auth/SignIn.tsx
  app/src/containers/Auth/SignUp.tsx
  app/src/locales/en.json
Labels: Review effort 3/5

#175 Pdf UI enhancement and translation
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Accessibility/ReportView.tsx
  app/src/utils/translator.ts
Labels: Review effort 3/5

#164 Pdf translation
  api/server.ts
  app/package-lock.json
  app/package.json
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Accessibility/ReportView.tsx
  app/src/utils/translator.ts
Labels: Possible security concern, Review effort 4/5

#174 Added https://hoppscotch.webability.io to allowedOrigins
  api/server.ts
Labels: Possible security concern, Review effort 1/5

#179 Email report pdf updated
  api/jobs/monthlyEmail.ts
  api/package.json
  api/services/allowedSites/allowedSites.service.ts
  api/utils/getWidgetSettings.ts
  api/utils/pdfGenerator.ts
  app/src/containers/Accessibility/AccessibilityReport.tsx
Labels: Review effort 4/5

#178 Fixes/security part 4
  api/middlewares/auth.middleware.ts
  api/middlewares/contentType.middleware.ts
  api/middlewares/limiters.middleware.ts
  api/middlewares/validation.middleware.ts
  api/package-lock.json
  api/package.json
  api/public/uploads/avatars/avatar-4-new-1618562539007-1663c71ebf8755d90c96.jpg
  api/public/uploads/avatars/avatar-4-new-1618915441060-1544620381-406-3-pinky-bao-tran-1-1544609498-width650height867.jpg
  api/repository/sites_allowed.repository.ts
  api/server.ts
  api/services/stripe/webhooks.servive.ts
  api/services/webToken/mongoVisitors.ts
  api/validations/email.validation.ts
  api/validations/stripe.validation.ts
  api/validations/widget.validation.ts
  app/src/utils/translator.ts
Labels: Possible security concern, Review effort 4/5

#182 Sanitize scanner domain in frontend like add domain modal
  api/services/allowedSites/allowedSites.service.ts
  api/utils/pdfGenerator.ts
  app/src/containers/Accessibility/AccessibilityReport.tsx
Labels: Possible security concern, Review effort 4/5

#183 Fallback pally api added
  api/helpers/accessibility.helper.ts
Labels: Review effort 2/5

#187 Rate Limit Fix
  api/graphql/schemas/impressions.schema.ts
Labels: Review effort 1/5

#190 Extract root domain funciton added to backend for widget 
  api/graphql/schemas/accessibilityReport.schema.ts
  api/graphql/schemas/allowedSites.schema.ts
  api/graphql/schemas/impressions.schema.ts
  api/graphql/schemas/sitesPlan.schema.ts
  api/graphql/schemas/uniqueToken.schema.ts
  api/graphql/schemas/uniqueVisitor.schema.ts
  api/repository/uniqueToken.repository.ts
  api/utils/domainUtils.ts
Labels: Review effort 3/5

#192 fixed package log json
  api/package-lock.json
  api/package.json
Labels: Review effort 1/5

#191 extract Root Domain funciton added to backend for widget 
  api/package-lock.json
  api/package.json
  api/repository/uniqueToken.repository.ts
  api/utils/domainUtils.ts
Labels: Review effort 3/5

#195 Fix Rate Limit
  api/graphql/directives/rateLimit.ts
  api/graphql/schemas/user.schema.ts
  api/middlewares/limiters.middleware.ts
  api/server.ts
Labels: Review effort 3/5, Possible security concern

#198 Fix/widget rate limiter
  api/graphql/directives/rateLimit.ts
  api/middlewares/limiters.middleware.ts
  api/server.ts
Labels: Review effort 2/5, Possible security concern

#200 user are allowed to scan any site + fixed success modal
  api/graphql/resolvers/accessibilityReport.resolver.ts
  app/src/containers/Accessibility/AccessibilityReport.tsx
Labels: Possible security concern, Review effort 4/5

#203 Domain validation added on insert impression url
  api/services/Impressions/impressions.service.ts
Labels: Review effort 2/5

#206 Persist domain scan across page navigation with completion notification
  app/src/App.tsx
  app/src/components/Common/Modal.tsx
  app/src/components/Common/ReportSuccessModal.tsx
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/ProblemReport/ProblemReport.tsx
  app/src/containers/Teams/editWidget.tsx
  app/src/features/report/reportSlice.ts
  app/src/features/rootReducer.ts
  app/src/utils/translator.ts
Labels: Review effort 4/5

#208 Revert "Persist domain scan across page navigation with completion notification"
  app/src/App.tsx
  app/src/components/Common/Modal.tsx
  app/src/components/Common/ReportSuccessModal.tsx
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/ProblemReport/ProblemReport.tsx
  app/src/containers/Teams/editWidget.tsx
  app/src/features/report/reportSlice.ts
  app/src/features/rootReducer.ts
  app/src/utils/translator.ts
Labels: Review effort 2/5

#209 Add universal font support for multilingual pd fs
  api/utils/translator.ts
  app/src/assets/fonts/NotoSans-normal.js
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Accessibility/ReportView.tsx
  app/src/utils/translator.ts
Labels: Review effort 3/5

#210 Add universal font support for multilingual pdfs
  api/utils/translator.ts
  app/src/assets/fonts/NotoSans-normal.js
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Accessibility/ReportView.tsx
  app/src/utils/translator.ts
Labels: Review effort 3/5

#212 Persist domain scan across page navigation with completion notification
  api/graphql/resolvers/accessibilityReport.resolver.ts
  api/graphql/schemas/accessibilityReport.schema.ts
  api/package.json
  app/package.json
  app/src/App.tsx
  app/src/components/Common/GlobalReportPolling.tsx
  app/src/components/Common/Modal.tsx
  app/src/components/Common/ReportSuccessModal.tsx
  app/src/config/store.ts
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/ProblemReport/ProblemReport.tsx
  app/src/containers/Teams/editWidget.tsx
  app/src/features/report/reportSlice.ts
  app/src/features/rootReducer.ts
  app/src/queries/accessibility/getAccessibilityReportByJobId.ts
  app/src/queries/accessibility/startAccessibilityReportJob.ts
  app/src/utils/localStorage.ts
Labels: Review effort 4/5

#213 Responsivness of view report page
  app/src/containers/Accessibility/ReportView.tsx
Labels: Review effort 3/5

#214 Responsivness of view report page
  app/src/containers/Accessibility/ReportView.tsx
Labels: Review effort 3/5

#215 Persist domain scan across page navigation with completion notification
  api/graphql/resolvers/accessibilityReport.resolver.ts
  api/graphql/schemas/accessibilityReport.schema.ts
  api/package.json
  app/package.json
  app/src/App.tsx
  app/src/components/Common/GlobalReportPolling.tsx
  app/src/config/store.ts
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/features/report/reportSlice.ts
  app/src/queries/accessibility/getAccessibilityReportByJobId.ts
  app/src/queries/accessibility/startAccessibilityReportJob.ts
  app/src/utils/localStorage.ts
Labels: Review effort 4/5
