Repository snayyar00/accessibility-widget, pull requests merged in 2025-06, with the labels that each got.

#120 Fix/logs
  api/Dockerfile
  api/nixpacks.toml
  api/package-lock.json
  api/package.json
  api/server.ts
  api/yarn-error.log
  app/Dockerfile
  app/nginx.conf
  app/nixpacks.toml
  app/package.json
  app/yarn.lock
  package-lock.json
Labels: Review effort 3/5, Possible security concern

#130 Fix PayloadTooLargeError: Increase request size limits from 2mb to 5mb
  api/server.ts
Labels: Review effort 2/5, Possible security concern

#127 Stage
  api/.npmrc
  api/config/preprocessing.config.ts
  api/server.ts
  app/.npmrc
  app/README.md
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Accessibility/ReportView.tsx
Labels: Review effort 2/5

#134 other feedback update
  app/src/containers/Teams/DeleteWarningModal.tsx
Labels: Review effort 2/5

#135 cascade deletion added
  api/server.ts
  api/services/deletion/cascade-delete.service.ts
Labels: Review effort 4/5

#136 Cancel flow
  api/repository/sites_allowed.repository.ts
  api/server.ts
  api/services/deletion/cascade-delete.service.ts
Labels: Possible security concern, Review effort 4/5

#137 deleteSitesPlan fix
  api/repository/sites_allowed.repository.ts
  api/services/allowedSites/plans-sites.service.ts
  api/services/stripe/subcription.service.ts
Labels: Review effort 3/5

#138 Cancel flow
  api/constants/billing.constant.ts
  api/repository/cancel_feedback.repository.ts
  api/repository/sites_allowed.repository.ts
  api/server.ts
  api/services/allowedSites/plans-sites.service.ts
  api/services/stripe/subcription.service.ts
  app/src/containers/Teams/DeleteWarningModal.tsx
  app/src/containers/Teams/DomainTable.tsx
Labels: Possible security concern, Review effort 4/5

#142 GraphQL timeout update
  api/server.ts
Labels: Review effort 2/5

#141 Feature/navigation accessibility seo improvements
  app/public/index.html
  app/src/components/Common/InitialAvatar.tsx
  app/src/components/Layout/Sidebar.tsx
  app/src/components/Layout/Topbar.tsx
  app/src/constants/toursteps.tsx
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Dashboard/Dashboard.tsx
  app/src/containers/Dashboard/TrialBannerAndModal.tsx
  app/src/containers/Profile/InformationSetting.tsx
  app/src/hooks/useTourGuidance.ts
  app/src/locales/en.json
  app/src/routes/index.tsx
Labels: Review effort 3/5

#144 feat: add translation resolver and statement generator tour steps
  api/config/translation.config.ts
  api/graphql/resolvers/translation.resolver.ts
  api/graphql/root.resolver.ts
  api/graphql/root.schema.ts
  api/graphql/schemas/translation.schema.ts
  api/services/translation/translation.service.ts
  app/src/constants/toursteps.tsx
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/StatementGenerator/StatementGenerator.tsx
  app/src/hooks/useTourGuidance.ts
  app/src/locales/en.json
  app/src/queries/translation/translateStatement.ts
  app/src/routes/index.tsx
Labels: Possible security concern, Review effort 4/5

#146 email with report pdf
  api/email-templates/accessReport.mjml
  api/email-templates/logo.png
  api/jobs/monthlyEmail.ts
  api/libs/mail.ts
  api/package-lock.json
  api/package.json
  api/services/allowedSites/allowedSites.service.ts
  api/utils/pdfGenerator.ts
Labels: Review effort 4/5

#147 email with report pdf
  api/email-templates/accessReport.mjml
  api/email-templates/logo.png
  api/jobs/monthlyEmail.ts
  api/libs/mail.ts
  api/package-lock.json
  api/package.json
  api/services/allowedSites/allowedSites.service.ts
  api/utils/pdfGenerator.ts
Labels: Possible security concern, Review effort 4/5

#148 Edit widget string mismatch
  app/src/components/Layout/Admin.tsx
  app/src/constants/index.js
  app/src/containers/Teams/editWidget.tsx
Labels: Review effort 2/5
