Repository snayyar00/accessibility-widget, pull requests merged in 2025-08, with the labels that each got.

#236 fix: unsubscribe link from emails now works properly
  api/routes/form.routes.ts
Labels: Review effort 2/5

#237 Prospect report code updated
  api/graphql/schemas/accessibilityReport.schema.ts
  api/helpers/accessibility.helper.ts
  api/services/accessibilityReport/accessibilityReport.service.ts
  api/services/accessibilityReport/enhancedProcessing.service.ts
  api/services/accessibilityReport/gptBatch.service.ts
  api/services/accessibilityReport/preprocessing.service.ts
  app/package.json
  app/public/images/report_icons/Mobility.svg
  app/public/images/report_icons/cognitive.svg
  app/public/images/report_icons/content.svg
  app/public/images/report_icons/eye.svg
  app/public/images/report_icons/forms.svg
  app/public/images/report_icons/low-vision.svg
  app/public/images/report_icons/navigation.svg
  app/public/images/report_icons/others.svg
  app/public/images/report_icons/shield.svg
  app/src/containers/Accessibility/AccessibilityIssuesGroup.tsx
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Accessibility/ReportView.tsx
  app/src/queries/accessibility/accessibility.ts
  app/src/queries/accessibility/fetchReportByR2Key.ts
  app/src/queries/accessibility/getAccessibilityReportByJobId.ts
  app/src/utils/translator.ts
Labels: Review effort 4/5

#238 Parsed codes from the new API
  api/graphql/schemas/accessibilityReport.schema.ts
  api/helpers/accessibility.helper.ts
  api/services/accessibilityReport/accessibilityReport.service.ts
  api/services/accessibilityReport/enhancedProcessing.service.ts
  api/services/accessibilityReport/gptBatch.service.ts
  api/services/accessibilityReport/preprocessing.service.ts
  app/src/containers/Accessibility/AccessibilityIssuesGroup.tsx
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Accessibility/ReportView.tsx
  app/src/queries/accessibility/accessibility.ts
  app/src/queries/accessibility/fetchReportByR2Key.ts
  app/src/queries/accessibility/getAccessibilityReportByJobId.ts
  app/src/utils/translator.ts
Labels: Review effort 4/5

#239 fix: resolve Day 1 email conditional subject line template compilation
  api/services/email/emailSequence.service.ts
Labels: Review effort 3/5

#241 fix: migrate email sequence subscription from newsletter_subscribers to user_notifications
  api/controllers/form.controller.ts
  api/graphql/resolvers/user.resolver.ts
  api/graphql/schemas/user.schema.ts
  api/jobs/monthlyEmail.ts
  api/repository/user.repository.ts
  api/services/allowedSites/allowedSites.service.ts
  api/services/authentication/register.service.ts
  api/services/email/emailSequence.service.ts
  api/services/problemReport/reportProblem.ts
  api/services/user/update-user.service.ts
  app/src/components/Layout/Topbar.tsx
Labels: Review effort 4/5

#242 fix: implement 24-hour interval email scheduling with Brevo scheduling
  api/controllers/form.controller.ts
  api/jobs/emailSequence.ts
  api/services/authentication/register.service.ts
  api/services/email/email.service.ts
  api/services/email/emailSequence.service.ts
  api/services/email/scheduledEmailTracker.service.ts
Labels: Possible security concern, Review effort 4/5

#245 Add proof of effort toolkit
  api/controllers/proof-of-effort.controller.ts
  api/email-templates/proofOfEffortToolkit.mjml
  api/graphql/resolvers/proofOfEffort.resolver.ts
  api/graphql/root.resolver.ts
  api/graphql/root.schema.ts
  api/graphql/schemas/accessibilityReport.schema.ts
  api/graphql/schemas/proofOfEffort.schema.ts
  api/helpers/accessibility.helper.ts
  api/routes/index.ts
  api/routes/proof-of-effort.routes.ts
  api/services/accessibilityReport/accessibilityReport.service.ts
  api/services/accessibilityReport/enhancedProcessing.service.ts
  api/services/accessibilityReport/gptBatch.service.ts
  api/services/accessibilityReport/preprocessing.service.ts
  app/package.json
  app/src/App.tsx
  app/src/components/Common/EmailModal.tsx
  app/src/components/Layout/Admin.tsx
  app/src/containers/Accessibility/AccessibilityIssuesGroup.tsx
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Accessibility/ReportView.tsx
  app/src/containers/ProofOfEffortToolkit/ProofOfEffortToolkit.tsx
  app/src/queries/accessibility/accessibility.ts
  app/src/queries/accessibility/fetchReportByR2Key.ts
  app/src/queries/accessibility/getAccessibilityReportByJobId.ts
  app/src/queries/proofOfEffort/sendToolkit.ts
  app/src/routes/index.tsx
  app/src/utils/translator.ts
Labels: Possible security concern, Review effort 4/5

#249 email validation function added
  api/controllers/proof-of-effort.controller.ts
  api/controllers/widget-installation.controller.ts
  api/graphql/resolvers/widget.resolver.ts
Labels: Review effort 2/5

#250 Prospect report revert fix
  api/controllers/proof-of-effort.controller.ts
  api/controllers/widget-installation.controller.ts
  api/graphql/resolvers/widget.resolver.ts
  api/graphql/schemas/accessibilityReport.schema.ts
  api/helpers/accessibility.helper.ts
  api/services/accessibilityReport/accessibilityReport.service.ts
  api/services/accessibilityReport/enhancedProcessing.service.ts
  api/services/accessibilityReport/gptBatch.service.ts
  api/services/accessibilityReport/preprocessing.service.ts
  app/src/components/Common/EmailModal.tsx
  app/src/containers/Accessibility/AccessibilityIssuesGroup.tsx
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Accessibility/ReportView.tsx
  app/src/containers/Installation/CodeContainer.tsx
  app/src/containers/ProofOfEffortToolkit/ProofOfEffortToolkit.tsx
  app/src/queries/accessibility/accessibility.ts
  app/src/queries/accessibility/fetchReportByR2Key.ts
  app/src/queries/accessibility/getAccessibilityReportByJobId.ts
  app/src/utils/translator.ts
Labels: Possible security concern, Review effort 4/5

#257 Add new tab called ai insights
  api/graphql/resolvers/domainAnalysis.resolver.ts
  api/graphql/root.resolver.ts
  api/graphql/root.schema.ts
  api/graphql/schemas/domainAnalysis.schema.ts
  api/services/domainAnalysis/domainAnalysis.service.ts
  app/src/containers/AIInsights/AIInsights.tsx
  app/src/queries/domainAnalysis/analyzeDomain.ts
  app/src/routes/index.tsx
Labels: Review effort 3/5, Possible security concern

#258 Add new tab called ai insights
  api/graphql/resolvers/domainAnalysis.resolver.ts
  api/graphql/root.resolver.ts
  api/graphql/root.schema.ts
  api/graphql/schemas/domainAnalysis.schema.ts
  api/services/domainAnalysis/domainAnalysis.service.ts
  app/src/components/Common/WhatsNewModal.tsx
  app/src/containers/AIInsights/AIInsights.tsx
  app/src/queries/domainAnalysis/analyzeDomain.ts
  app/src/routes/index.tsx
Labels: Review effort 3/5, Possible security concern

#259 Ui updated , beta tag added , auto scroll added
  app/src/components/Layout/Sidebar.tsx
  app/src/containers/AIInsights/AIInsights.tsx
  app/src/routes/index.tsx
Labels: Review effort 2/5

#260 Beta tag UI responsive
  app/src/containers/AIInsights/AIInsights.tsx
Labels: Review effort 1/5

#261 fix: enhance email sequence recovery to handle unlimited gap lengths
  api/services/email/emailSequence.service.ts
  api/services/user/update-user.service.ts
Labels: Review effort 3/5

#262 fix: Enhanced email recovery system with re-scheduling
  api/services/email/emailSequence.service.ts
  api/services/email/scheduledEmailTracker.service.ts
Labels: Review effort 3/5

#263 Fix email delivery tracking: prevent premature sent marking
  api/jobs/emailSequence.ts
  api/services/email/emailDeliveryStatus.service.ts
  api/services/email/emailSequence.service.ts
  api/services/email/scheduledEmailTracker.service.ts
Labels: Review effort 3/5

#266 fix: prevent email duplication by checking scheduled emails before cr…
  api/services/email/emailSequence.service.ts
  api/services/email/scheduledEmailTracker.service.ts
Labels: Review effort 2/5

#269 Non intrusive text only widget
  app/src/containers/Installation/CodeContainer.tsx
Labels: Review effort 2/5

#270 Install page script Note
  app/src/containers/Installation/CodeContainer.tsx
Labels: Review effort 1/5

#255 Fix unsubscribe URLs to use backend endpoint
  api/jobs/emailSequence.ts
  api/services/email/emailDeliveryStatus.service.ts
  api/services/email/emailSequence.service.ts
  api/services/email/scheduledEmailTracker.service.ts
  api/services/user/update-user.service.ts
Labels: Review effort 2/5

#271 fix: simplify email sequence to immediate sending with database tracking
  api/controllers/form.controller.ts
  api/email-templates/day14AccessibilityFixes.mjml
  api/email-templates/day28Automation.mjml
  api/email-templates/day2AuditReport.mjml
  api/email-templates/day3FAQ.mjml
  api/email-templates/day7ProductWalkthrough.mjml
  api/email-templates/day90Milestones.mjml
  api/email-templates/week10SuccessStory.mjml
  api/email-templates/week6CustomerSuccess.mjml
  api/jobs/emailSequence.ts
  api/repository/user.repository.ts
  api/services/authentication/register.service.ts
  api/services/email/email.service.ts
  api/services/email/emailDeliveryStatus.service.ts
  api/services/email/emailSequence.service.ts
  api/services/email/scheduledEmailTracker.service.ts
  api/services/user/update-user.service.ts
Labels: Review effort 3/5

#273 Optimize email sequence processing and database operations
  api/repository/user.repository.ts
  api/services/email/emailSequence.service.ts
Labels: Review effort 3/5

#272 fix: simplify email sequence to immediate sending with database tracking
  api/controllers/form.controller.ts
  api/email-templates/day14AccessibilityFixes.mjml
  api/email-templates/day28Automation.mjml
  api/email-templates/day2AuditReport.mjml
  api/email-templates/day3FAQ.mjml
  api/email-templates/day7ProductWalkthrough.mjml
  api/email-templates/day90Milestones.mjml
  api/email-templates/week10SuccessStory.mjml
  api/email-templates/week6CustomerSuccess.mjml
  api/jobs/emailSequence.ts
  api/repository/user.repository.ts
  api/services/authentication/register.service.ts
  api/services/email/email.service.ts
  api/services/email/emailDeliveryStatus.service.ts
  api/services/email/emailSequence.service.ts
  api/services/email/scheduledEmailTracker.service.ts
  api/services/user/update-user.service.ts
Labels: Review effort 3/5

#278 Quality model used for the gpt batch processing
  api/services/accessibilityReport/gptBatch.service.ts
Labels: Review effort 2/5

#279 wcag_code wont be affected by the gpt batch processing
  api/services/accessibilityReport/gptBatch.service.ts
Labels: Review effort 2/5

#280 if response is empty it will retry and if it still fails it will use…
  api/helpers/accessibility.helper.ts
Labels: Review effort 2/5, Possible security concern

#281 Structured page breaks added
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Accessibility/ReportView.tsx
  app/src/containers/ProofOfEffortToolkit/ProofOfEffortToolkit.tsx
Labels: Review effort 5/5

#277 License owner info added
  api/graphql/resolvers/user.resolver.ts
  api/graphql/schemas/user.schema.ts
  api/repository/user.repository.ts
  api/services/user/license-owner.service.ts
  app/src/containers/LicenseOwnerInfo/index.tsx
  app/src/locales/en.json
  app/src/queries/user/getLicenseOwnerInfo.ts
  app/src/queries/user/updateLicenseOwnerInfo.ts
  app/src/routes/index.tsx
Labels: Review effort 3/5, Possible security concern

#284 reapplied reverted changes - links added to cards, no openner/noreffer , analyzer
  api/graphql/resolvers/accessibilityReport.resolver.ts
  api/helpers/accessibility.helper.ts
  api/services/accessibilityReport/accessibilityReport.service.ts
  app/src/components/Common/WhatsNewModal.tsx
Labels: Review effort 3/5

#286 Fix WCAG issue and improve UI/UX for chatbot and report view
  api/controllers/chat.controller.ts
  api/routes/chat.routes.ts
  api/routes/index.ts
  app/src/containers/Accessibility/FloatingChatbot.tsx
  app/src/containers/Accessibility/ReportView.tsx
Labels: Review effort 2/5
