Repository snayyar00/accessibility-widget, pull requests merged in 2025-09, with the labels that each got.

#295 Identified Issues count fixed will now use axe too
  api/jobs/monthlyEmail.ts
  api/services/allowedSites/allowedSites.service.ts
Labels: Review effort 2/5

#296 CLICKHOUSE_DISABLE_FLAG added
  api/config/clickhouse.config.ts
  api/services/Impressions/impressions.service.ts
  api/services/uniqueVisitors/uniqueVisitor.service.ts
  api/utils/database.utils.ts
Labels: Review effort 2/5

#297 option added for full ( with cache) and slow(without cache) scan
  api/graphql/resolvers/accessibilityReport.resolver.ts
  api/graphql/schemas/accessibilityReport.schema.ts
  api/helpers/accessibility.helper.ts
  api/services/accessibilityReport/accessibilityReport.service.ts
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Accessibility/FloatingChatbot.tsx
  app/src/containers/Accessibility/ReportView.tsx
  app/src/queries/accessibility/startAccessibilityReportJob.ts
Labels: Review effort 2/5

#305 Unsubscribe links added in email
  api/controllers/form.controller.ts
  api/email-templates/accessReport.mjml
  api/email-templates/problemReported.mjml
  api/jobs/monthlyEmail.ts
  api/routes/form.routes.ts
  api/services/allowedSites/allowedSites.service.ts
  api/services/email/emailSequence.service.ts
  api/services/monitoring/monitoring.service.ts
  api/services/problemReport/reportProblem.ts
  api/utils/secure-unsubscribe.utils.ts
Labels: Review effort 3/5, Possible security concern

#311 Ai readiness analysis
  api/graphql/resolvers/aiReadiness.resolver.ts
  api/graphql/root.resolver.ts
  api/graphql/root.schema.ts
  api/graphql/schemas/aiReadiness.schema.ts
  api/package.json
  api/services/ai-readiness.service.ts
  api/utils/browserbase-service.ts
  app/src/components/AIReadiness/ControlPanel.tsx
  app/src/components/AIReadiness/MetricBars.tsx
  app/src/components/AIReadiness/RadarChart.tsx
  app/src/components/AIReadiness/ScoreChart.tsx
  app/src/containers/AIInsights/AIInsights.tsx
  app/src/queries/aiReadiness/analyzeAIReadiness.ts
Labels: Possible security concern, Review effort 4/5

#315 Screenshot using browserbase
  api/graphql/schemas/accessibilityReport.schema.ts
  api/helpers/accessibility.helper.ts
  api/jobs/monthlyEmail.ts
  api/services/accessibilityReport/accessibilityReport.service.ts
  api/services/accessibilityReport/enhancedProcessing.service.ts
  api/services/accessibilityReport/gptBatch.service.ts
  api/services/accessibilityReport/preprocessing.service.ts
  api/services/ai-readiness.service.ts
  app/src/components/AIReadiness/ScoreChart.tsx
  app/src/containers/Accessibility/ReportView.tsx
  app/src/containers/Installation/CodeContainer.tsx
  app/src/containers/Teams/CustomizeWidget.tsx
  app/src/generated/graphql.ts
  app/src/queries/accessibility/accessibility.ts
  app/src/queries/accessibility/fetchReportByR2Key.ts
  app/src/queries/accessibility/getAccessibilityReportByJobId.ts
Labels: Possible security concern, Review effort 4/5

#319 proxy added and Remove modals in ss using browserbase
  api/helpers/accessibility.helper.ts
Labels: Review effort 2/5

#321 fix:auth ads image fix
  .gitignore
  app/src/components/Auth/AuthAds.tsx
Labels: Review effort 1/5

#323 Pdf report design update
  app/src/assets/images/1_issues_icon.png
  app/src/assets/images/2_issues_icon.png
  app/src/assets/images/3_issues_icon.png
  app/src/assets/images/compliant_success.png
  app/src/assets/images/critical_icon.png
  app/src/assets/images/green_success.png
  app/src/assets/images/message_icon.png
  app/src/assets/images/mild_icon.png
  app/src/assets/images/moderate_icon.png
  app/src/containers/Accessibility/AccessibilityReport.tsx
  app/src/containers/Accessibility/ReportView.tsx
  app/src/containers/ProofOfEffortToolkit/ProofOfEffortToolkit.tsx
  app/src/utils/generatePDF.ts
Labels: Review effort 4/5
